# Generated by Django 4.2.6 on 2023-10-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aensongaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(default=0)),
                ('our_goal', models.IntegerField(default=0)),
                ('raised', models.IntegerField(default=0)),
            ],
        ),
    ]
