# Generated by Django 4.2.6 on 2023-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aensongaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='pictures/ceo')),
                ('about_me', models.TextField(max_length=500)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
